#创建tensor

In [0]:
import tensorflow as tf
import numpy as np


In [2]:
#创建constant常量
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant(2.,dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [5]:
#创建bool型常量
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [6]:
#创建string型常量
tf.constant('hello')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

# tensor的属性

In [11]:
#当前tensor运行的设备（cpu/gpu）
with tf.device('cpu'):
  a=tf.constant([1])
with tf.device('gpu'):
  b=tf.range(4)
print(a.device)
print(b.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [13]:
#cpu和gpu转换
aa=a.gpu()
aa.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [16]:
#转化为numpy类型
bb=b.numpy()
bb

array([0, 1, 2, 3], dtype=int32)

In [17]:
#查看维度
bb.ndim

1

In [22]:
#判断是否为tensor
tf.is_tensor(b) , tf.is_tensor(b.numpy())

(True, False)

In [23]:
#判断数据类型
b.dtype==tf.double

False

#数据类型转化

In [24]:
a=np.arange(5)
a.dtype

dtype('int64')

In [26]:
#转化为tensor
aa=tf.convert_to_tensor(a)
aaa=tf.convert_to_tensor(a,dtype=tf.int32)
aa,aaa

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>)

In [29]:
#更改tensor的数据类型
tf.cast(aa,dtype=tf.double)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [30]:
#整型和bool的转换
i=tf.constant([0,1])
tf.cast(i,dtype=tf.bool)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

#Variable类型

In [0]:
在TensorFlow中，变量(Variable)是特殊的张量(Tensor)，它的值可以是一个任何类型和形状的张量。
与其他张量不同，变量存在于单个 session.run 调用的上下文之外，也就是说，变量存储的是持久张量，当训练模型时，用变量来存储和更新参数。除此之外，在调用op之前，所有变量都应被显式地初始化过。

In [33]:
v = tf.Variable([1,2,3])   #创建变量v，为一个array
print(v)  #查看v的shape，不是v的值。结果是： <tf.Variable 'Variable:0' shape=(3,) dtype=int32_ref>
z = tf.Variable(tf.zeros([20]))  #初始化一个形状为[20]的张量， 里面的元素值全部为0.

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
