In [0]:
import tensorflow as tf



1.   sort/argsort
2.   Topk
3. Top-5 ACC



# sort/argsort

In [3]:
a=tf.random.shuffle(tf.range(5))
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 0, 4, 1, 2], dtype=int32)>

In [4]:
tf.sort(a,direction='DESCENDING')#降序

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0], dtype=int32)>

In [5]:
tf.sort(a,direction="ASCENDING")#升序

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [6]:
tf.argsort(a,direction="ASCENDING")#得到升序排列后的索引

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 4, 0, 2], dtype=int32)>

In [7]:
tf.argsort(a,direction="DESCENDING")#得到降序排列后的索引

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 0, 4, 3, 1], dtype=int32)>

# Top_k（最大/最小前k个）

In [0]:
b=tf.constant([[3,2,1,5],[2,1,4,6]])

In [0]:
bb=tf.math.top_k(b,2)
#返回结果是两个，Values是值，indices是索引

In [13]:
bb.indices,bb.values

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 0],
        [3, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 3],
        [6, 4]], dtype=int32)>)