In [0]:
import tensorflow as tf

# 加减乘除，取余，整除

In [0]:
a=tf.fill([2,2],2.)
b=tf.ones([2,2])

In [4]:
a+b,a-b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [5]:
a*b,a/b   #均是对应元素进行操作

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

In [6]:
b//a #整除，除后取整数

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
a%b #取余

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

# log对数和exp指数运算

如果要实现非e为底数的log运算，则需要用log(x)/log(y)

In [8]:
tf.math.log(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [9]:
tf.math.exp(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

# 幂次运算和开放运算

In [10]:
tf.math.pow(a,4)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[16., 16.],
       [16., 16.]], dtype=float32)>

或者

In [11]:
a**4

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[16., 16.],
       [16., 16.]], dtype=float32)>

In [12]:
tf.math.sqrt(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

# 矩阵运算

In [13]:
a@b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

或者

In [14]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

当多维张量使用矩阵运算时，会把张量的最后两维当作矩阵来运算

In [0]:
c=tf.random.normal([3,9,3,2])
d=tf.random.normal([3,9,2,3])

In [16]:
(c@d).shape

TensorShape([3, 9, 3, 3])

In [20]:
dd=tf.random.normal([2,3])
# 这时候直接c@dd是不可以的，tf不会自动使用隐式broadcast
ddd=tf.broadcast_to(dd,[3,9,2,3])
(ddd@c).shape

TensorShape([3, 9, 2, 2])