In [0]:
import tensorflow as tf

# 向量的范数

向量的二范数

In [0]:
a=tf.ones([2,2])

In [0]:
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

指定维度

In [0]:
tf.norm(a,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

向量的一范数

In [0]:
tf.norm(a,ord=1,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

# 张量某一维度最大值最小值平均值

In [0]:
b=tf.random.normal([4,10])

如果不加axis参数，那么求得的就是所有元素的最大值、最小值、均值

In [0]:
tf.reduce_max(b),tf.reduce_min(b),tf.reduce_mean(b)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.6853324>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.112137>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.084009126>)

指定维度后，计算最大值/最小值/均值，就会得到一个降维的结果

In [0]:
tf.reduce_max(b,axis=0)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.46189705,  0.46633697,  0.55208635,  1.2575941 ,  1.2874742 ,
        1.6853324 ,  0.4323803 ,  1.2548473 ,  0.62353814, -0.18367732],
      dtype=float32)>

In [0]:
tf.reduce_max(b,axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.6853324, 1.2575941, 1.1790547, 1.2874742], dtype=float32)>

# 返回极值的索引

tf.argmax(vector, 1)：返回的是vector中的最大值的索引号，如果vector是一个向量，那就返回一个值，如果是一个矩阵，那就返回一个向量，这个向量的每一个维度都是相对应矩阵行的最大值元素的索引号。

In [0]:
tf.argmax(b,axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 3, 7, 4])>

In [0]:
tf.argmin(b,axis=0)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 0, 2, 0, 2, 3, 1, 1, 3, 0])>

# 张量比较

In [0]:
c=tf.ones([2,3])
d=tf.random.normal([2,3])

In [0]:
e=tf.equal(c,d)

可以求得匹配正确的个数

In [0]:
tf.reduce_sum(tf.cast(e,dtype=tf.int32))

<tf.Tensor: shape=(), dtype=int32, numpy=0>

# 去重复元素

In [0]:
f=tf.constant([3,4,2,4,7,6,7])

y,idx分别是去除重复元素之后的张量以及原来的张量中的元素在去除重复的张量里面的索引

In [0]:
y,idx=tf.unique(f)

In [0]:
y,idx

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 2, 7, 6], dtype=int32)>,
 <tf.Tensor: shape=(7,), dtype=int32, numpy=array([0, 1, 2, 1, 3, 4, 3], dtype=int32)>)