In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#索引

##简单索引[ ]

In [0]:
a=tf.ones([2,3,4,5])

In [9]:
a[0][1],a[0][0][1]

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>)

或者这样

In [10]:
a[0,0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

##gather按索引收集

In [0]:
#假设c有4个班级，每个班级35个学生，每个学生有8门成绩
c=tf.ones([4,35,8])

收集第2、3号（从1号开始）班级的成绩

In [33]:
cc=tf.gather(c,axis=0,indices=[1,2])
cc.shape

TensorShape([2, 35, 8])

上式等同于

In [0]:
c[1:3]

但是，gather的索引顺序是按indices里面的索引顺序来的。也就是说，indices[2,3,4]跟indices[3,4,2]得到的结果是不一样的

axis代表抽取的哪一个维度，例如下面代码表示在各个班级里按顺序抽取第4、6、1、23、4号同学的所有成绩

In [39]:
ccc=tf.gather(c,axis=1,indices=[4,6,1,23,4])
ccc.shape

TensorShape([4, 5, 8])

##gather_nd在多个维度同时收集

如果我们想抽取1号班级2号学生，3号班级8好学生。。。的成绩，则需要在多个维度进行抽取

In [44]:
#抽取0号班级全部学生的成绩
cccc=tf.gather_nd(c,[0])
cccc.shape

TensorShape([35, 8])

In [46]:
#抽取0号班级1号学生的成绩
ccccc=tf.gather_nd(c,[0,1])
ccccc.shape

TensorShape([8])

两级[ ]中，最外面的[ ]代表抽取结果的list，里面有多少个[ ]，就会有多少样本。第二级[ ]表示每个样本的索引

In [57]:
#抽取0号班级7号学生、1号班级4号学生的所有成绩
ccccccc=tf.gather_nd(c,[[0,7],[1,4]])
ccccccc.shape

TensorShape([2, 8])

In [54]:
#抽取0号班级1号学生、1号班级8号学生的某一门成绩
cccccc=tf.gather_nd(c,[[0,1,7],[1,8,7]])
cccccc.shape

TensorShape([2])

下面代码跟上面代码差不多，但它多了一层[ ]，就是把结果放入了一个list中的list

In [55]:
ccccccc=tf.gather_nd(c,[[[0,1,7],[1,8,7]]])
ccccccc.shape

TensorShape([1, 2])

#切片

##简单切片:

In [14]:
b=tf.range(10)
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

不包含冒号后面的index

In [12]:
b[-1:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [13]:
b[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [15]:
b[4:8]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [16]:
b[:-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [22]:
a[1,:,:,:].shape

TensorShape([3, 4, 5])

##每隔step取点（双冒号）

In [25]:
a[:,::2,::2,1]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

##逆序

In [26]:
c=tf.range(6)
c[::-1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([5, 4, 3, 2, 1, 0], dtype=int32)>

In [27]:
tf.sort(c)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

##省略号快速切片

省略号代替任意长的冒号

In [28]:
a[0,...]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [29]:
a[0,...,1]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>